### ISSUE TITLE
Extension on `UIColor`

### ISSUE THREAD

**Issue by MarkQSchultz** [jathu/sweetercolor#4]
This is not really an issue, but thought this would be the place to have a discussion.

Why not build all of this as an extension of `UIColor`? It seems like most of the methods you've written start by fetching the `color` property and then accessing information from that.

**Comment by jathu** [comment]
I initially made this for one of my own projects and I had some issues with creating custom constructors with UIColor. However, if I want this project to go anywhere, it would be wise to just extend UIColor. I will have some time around next week, so I think I'll make the changes then. Thanks! :+1:

**Comment by jathu** [comment]
Made the changes (https://github.com/jathu/sweetercolor/pull/5), thanks!

**Comment by MarkQSchultz** [comment]
Cool!
