### ISSUE TITLE
[Feature request] Hex support

### ISSUE THREAD

**Issue by ghost** [jathu/sweetercolor#6]
Can we import the Hex feature from https://github.com/hyperoslo/Hue to use hex colors with `#`. 

The current format `0xFBF002` isn't the normal hex format outside of UIKit.

**Comment by jathu** [comment]
I made a choice to use ```Int: 0xHEX``` because it seems more elegant and more importantly, it makes parsing it much easier. However, I can see the benefit of having a string hex initializer as it can be used dynamically. I'll see what I can do.

**Comment by droidery** [comment]
Thanks. I'm using SweeterColor plus the convenience method for hex with `#` from Hue and it's working well as it just returns a UIColor parsed to RGB.

**Comment by jathu** [comment]
The change has been made! https://github.com/jathu/sweetercolor/commit/42e9f5f55579b02eed6f482f4ff91400d441b7d2
