### ISSUE TITLE
Swift version (3) no longer supported in XCode

### ISSUE THREAD

**Issue by salqadri** [jathu/sweetercolor#9]
I tried installing this pod but I get the following error in XCode:

```
SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0.
```

Could you please add support for the newer Swift versions?

**Comment by jathu** [comment]
Hey @salqadri, thanks for reporting the issue. Unfortunately, I haven't kept up with the Swift updates and won't have time to upgrade this library in the neat future.

**Comment by salqadri** [comment]
Ok np; fwiw I copied the file over into my project and it works fine without any code changes in the latest swift.

**Comment by jathu** [comment]
Great, glad it worked out!
